---

- name: become block
  become: yes
  block:

#    - name: Delete k3s if already present
#      file:
#        path: /usr/local/bin/k3s
#        state: absent

    - name: Download k3s binary x64
      notify: k3s restart
      get_url:
          url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s
          checksum: sha256:https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/sha256sum-amd64.txt
          dest: /usr/local/bin/k3s
          owner: root
          group: root
          mode: 755
    #  when: ( ansible_facts.userspace_architecture == "x86_64" )
      when: ( ansible_facts.architecture == "x86_64" )

    - name: Download k3s binary arm64
      notify: k3s restart
      get_url:
          url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-arm64
          checksum: sha256:https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/sha256sum-arm64.txt
          dest: /usr/local/bin/k3s
          owner: root
          group: root
          mode: 755
      when: ( ansible_facts.architecture is search("arm") )
              and
            ( ansible_facts.userspace_bits == "64" )

    - name: Download k3s binary armhf
      notify: k3s restart
      get_url:
          url: https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/k3s-armhf
          checksum: sha256:https://github.com/rancher/k3s/releases/download/{{ k3s_version }}/sha256sum-arm.txt
          dest: /usr/local/bin/k3s
          owner: root
          group: root
          mode: 755
      when: ( ansible_facts.architecture is search("arm") )
              and
            ( ansible_facts.userspace_bits == "32" )

    - name: Create kubectl symlink
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/kubectl
        state: link

    - name: Create crictl symlink
      file:
        src: /usr/local/bin/k3s
        dest: /usr/local/bin/crictl
        state: link